package de.kiezatlas.deepamehta.etl;

import java.util.HashMap;
import java.util.Map;



public class Transformation {

    public static Map<String, String> CRITERIA_MAP = new HashMap();
    public static Map<String, String> CATEGORY_MAP = new HashMap();

    static {
        putCrit("t-253478",           "ka2.criteria.thema.facet");          // Mitte
        putCrit("t-239975",           "ka2.criteria.thema.facet");          // FrKr
        putCrit("tt-ka-kategorie",    "ka2.criteria.thema.facet");          // TeSch
        putCrit("t-229903",           "ka2.criteria.thema.facet");          // TreKö
        putCrit("t-181709",           "ka2.criteria.thema.facet");          // Neuk
        putCrit("t-181711",           "ka2.criteria.thema.facet");          // Neuk
        putCrit("t-230488",           "ka2.criteria.thema.facet");          // Pankow
        putCrit("t-202836",           "ka2.criteria.thema.facet");          // ChaWi
        putCrit("t-96787",            "ka2.criteria.thema.facet");          // Span
        putCrit("t-307982",           "ka2.criteria.thema.facet");          // SteZe
        putCrit("t-307988",           "ka2.criteria.thema.facet");          // SteZe
        putCrit("t-188950",           "ka2.criteria.thema.facet");          // Li
        putCrit("t-214403",           "ka2.criteria.thema.facet");          // Li
        putCrit("t-253482",           "ka2.criteria.angebot.facet");        // Mitte
        putCrit("t-239977",           "ka2.criteria.angebot.facet");        // FrKr
        putCrit("tt-ka-angebot",      "ka2.criteria.angebot.facet");        // TeSch
        putCrit("t-229905",           "ka2.criteria.angebot.facet");        // TreKö
        putCrit("t-230490",           "ka2.criteria.angebot.facet");        // Pankow
        putCrit("t-202838",           "ka2.criteria.angebot.facet");        // ChaWi
        putCrit("t-96789",            "ka2.criteria.angebot.facet");        // Span
        putCrit("t-307990",           "ka2.criteria.angebot.facet");        // SteZe
        putCrit("t-188952",           "ka2.criteria.angebot.facet");        // Li
        putCrit("t-214437",           "ka2.criteria.angebot.facet");        // Li
        putCrit("t-253480",           "ka2.criteria.zielgruppe.facet");     // Mitte
        putCrit("t-239979",           "ka2.criteria.zielgruppe.facet");     // FrKr
        putCrit("tt-ka-altersgruppe", "ka2.criteria.zielgruppe.facet");     // TeSch
        putCrit("t-229907",           "ka2.criteria.zielgruppe.facet");     // TreKö
        putCrit("t-230492",           "ka2.criteria.zielgruppe.facet");     // Pankow
        putCrit("t-202840",           "ka2.criteria.zielgruppe.facet");     // ChaWi
        putCrit("t-96791",            "ka2.criteria.zielgruppe.facet");     // Span
        putCrit("t-307986",           "ka2.criteria.zielgruppe.facet");     // SteZe
        putCrit("t-188954",           "ka2.criteria.zielgruppe.facet");     // Li
        putCrit("t-181713",           "ka2.criteria.traeger.facet");        // Neuk
        putCrit("t-1220610",          "ka2.criteria.ueberregional.facet");  // FrKr
    }

    static {
        // Themen
        putCat("t-253525",   "ka2.category.ausbildung_und_arbeit");                                 // Mitte
        putCat("t-240011",   "ka2.category.ausbildung_und_arbeit");                                 // FrKr
        putCat("t-ka-kat5",  "ka2.category.ausbildung_und_arbeit");                                 // TeSch
        putCat("t-229947",   "ka2.category.ausbildung_und_arbeit");                                 // TreKö
        putCat("t-202851",   "ka2.category.ausbildung_und_arbeit");                                 // ChaWi
        putCat("t-96796",    "ka2.category.ausbildung_und_arbeit");                                 // Span
        putCat("t-308014",   "ka2.category.ausbildung_und_arbeit");                                 // SteZe
        putCat("t-188991",   "ka2.category.ausbildung_und_arbeit");                                 // Li
        putCat("t-253526",   "ka2.category.beratung");                                              // Mitte
        putCat("t-240012",   "ka2.category.beratung");                                              // FrKr
        putCat("t-ka-kat6",  "ka2.category.beratung");                                              // TeSch
        putCat("t-230424",   "ka2.category.beratung");                                              // TreKö
        putCat("t-202852",   "ka2.category.beratung");                                              // ChaWi
        putCat("t-96797",    "ka2.category.beratung");                                              // Span
        putCat("t-188992",   "ka2.category.beratung");                                              // Li
        putCat("t-929829",   "ka2.category.buergerhaushalt");                                       // Li
        putCat("t-253527",   "ka2.category.familie");                                               // Mitte
        putCat("t-240013",   "ka2.category.familie");                                               // FrKr
        putCat("t-ka-kat1",  "ka2.category.familie");                                               // TeSch
        putCat("t-230425",   "ka2.category.familie");                                               // TreKö
        putCat("t-181743",   "ka2.category.familie");                                               // Neuk
        putCat("t-202853",   "ka2.category.familie");                                               // ChaWi
        putCat("t-96798",    "ka2.category.familie");                                               // Span
        putCat("t-188993",   "ka2.category.familie");                                               // Li
        putCat("t-777382",   "ka2.category.familien_und_nachbarschaftszentren");                    // Pankow
        putCat("t-308016",   "ka2.category.familien_und_nachbarschaftszentren");                    // SteZe
        putCat("t-507124",   "ka2.category.frauen");                                                // Mitte
        putCat("t-253608",   "ka2.category.frauen");                                                // Pankow
        putCat("t-308017",   "ka2.category.frauen");                                                // SteZe
        putCat("t-188994",   "ka2.category.frauen");                                                // Li
        putCat("t-230577",   "ka2.category.freie_traeger_der_hilfen_zur_erziehung");                // Pankow
        putCat("t-181731",   "ka2.category.freizeit");                                              // Neuk
        putCat("t-181745",   "ka2.category.gemeinwesen");                                           // Neuk
        putCat("t-181734",   "ka2.category.geschaeftsstelle");                                      // Neuk
        putCat("t-240014",   "ka2.category.gesundheit");                                            // FrKr
        putCat("t-308018",   "ka2.category.gesundheit");                                            // SteZe
        putCat("t-253528",   "ka2.category.gesundheit_und_behinderung");                            // Mitte
        putCat("t-ka-kat7",  "ka2.category.gesundheit_und_behinderung");                            // TeSch
        putCat("t-230426",   "ka2.category.gesundheit_und_behinderung");                            // TreKö
        putCat("t-202854",   "ka2.category.gesundheit_und_behinderung");                            // ChaWi
        putCat("t-96799",    "ka2.category.gesundheit_und_behinderung");                            // Span
        putCat("t-188995",   "ka2.category.gesundheit_und_behinderung");                            // Li
        putCat("t-230583",   "ka2.category.gesundheit_und_soziales");                               // Pankow
        putCat("t-ka-kat17", "ka2.category.gewerbe");                                               // TeSch
        putCat("t-181732",   "ka2.category.hilfen");                                                // Neuk
        putCat("t-308019",   "ka2.category.hochschulen");                                           // SteZe
        putCat("t-198186",   "ka2.category.hochschulen");                                           // Li
        putCat("t-240016",   "ka2.category.jugend");                                                // FrKr
        putCat("t-6246",     "ka2.category.jugend");                                                // TeSch
        putCat("t-230427",   "ka2.category.jugend");                                                // TreKö
        putCat("t-181742",   "ka2.category.jugend");                                                // Neuk
        putCat("t-202855",   "ka2.category.jugend");                                                // ChaWi
        putCat("t-96801",    "ka2.category.jugend");                                                // Span
        putCat("t-188997",   "ka2.category.jugend");                                                // Li
        putCat("t-253530",   "ka2.category.jugendamt");                                             // Mitte
        putCat("t-240017",   "ka2.category.jugendamt");                                             // FrKr
        putCat("t-ka-kat8",  "ka2.category.jugendamt");                                             // TeSch
        putCat("t-230437",   "ka2.category.jugendamt");                                             // TreKö
        putCat("t-202856",   "ka2.category.jugendamt");                                             // ChaWi
        putCat("t-96802",    "ka2.category.jugendamt");                                             // Span
        putCat("t-96800",    "ka2.category.jugendhilfeangebote");                                   // Span
        putCat("t-230576",   "ka2.category.thema_jugendsozialarbeit");                              // Pankow
        putCat("t-181733",   "ka2.category.kieztreff");                                             // Neuk
        putCat("t-253529",   "ka2.category.kinder_und_jugendfreizeit");                             // Mitte
        putCat("t-230575",   "ka2.category.kinder_und_jugendfreizeit");                             // Pankow
        putCat("t-569792",   "ka2.category.kinder_und_jugendfreizeit");                             // SteZe
        putCat("t-308021",   "ka2.category.kinder_und_jugendfreizeit");                             // SteZe
        putCat("t-240018",   "ka2.category.kinder");                                                // FrKr
        putCat("t-ka-kat2",  "ka2.category.kinder");                                                // TeSch
        putCat("t-230438",   "ka2.category.kinder");                                                // TreKö
        putCat("t-181741",   "ka2.category.kinder");                                                // Neuk
        putCat("t-202857",   "ka2.category.kinder");                                                // ChaWi
        putCat("t-96803",    "ka2.category.kinder");                                                // Span
        putCat("t-188998",   "ka2.category.kinder");                                                // Li
        putCat("t-253531",   "ka2.category.kinderbetreuung");                                       // Mitte
        putCat("t-240019",   "ka2.category.kinderbetreuung");                                       // FrKr
        putCat("t-ka-kat9",  "ka2.category.kinderbetreuung");                                       // TeSch
        putCat("t-230439",   "ka2.category.kinderbetreuung");                                       // TreKö
        putCat("t-202858",   "ka2.category.kinderbetreuung");                                       // ChaWi
        putCat("t-96804",    "ka2.category.kinderbetreuung");                                       // Span
        putCat("t-230574",   "ka2.category.kindertagesstaetten");                                   // Pankow
        putCat("t-569787",   "ka2.category.kindertagesstaetten");                                   // SteZe
        putCat("t-230586",   "ka2.category.kirchengemeinden");                                      // Pankow
        putCat("t-253532",   "ka2.category.kultur_und_bildung");                                    // Mitte
        putCat("t-240020",   "ka2.category.kultur_und_bildung");                                    // FrKr
        putCat("t-ka-kat10", "ka2.category.kultur_und_bildung");                                    // TeSch
        putCat("t-230440",   "ka2.category.kultur_und_bildung");                                    // TreKö
        putCat("t-230582",   "ka2.category.kultur_und_bildung");                                    // Pankow
        putCat("t-202859",   "ka2.category.kultur_und_bildung");                                    // ChaWi
        putCat("t-96805",    "ka2.category.kultur_und_bildung");                                    // Span
        putCat("t-188999",   "ka2.category.kultur_und_bildung");                                    // Li
        putCat("t-308022",   "ka2.category.kultur_und_freizeit");                                   // SteZe
        putCat("t-308023",   "ka2.category.maenner");                                               // SteZe
        putCat("t-240015",   "ka2.category.menschen_mit_behinderungen");                            // FrKr
        putCat("t-308015",   "ka2.category.menschen_mit_behinderungen");                            // SteZe
        putCat("t-253610",   "ka2.category.migration_und_integration");                             // Pankow
        putCat("t-308024",   "ka2.category.migration_und_integration");                             // SteZe
        putCat("t-189000",   "ka2.category.migration_und_integration");                             // Li
        putCat("t-253533",   "ka2.category.nachbarschaft_und_stadtteil");                           // Mitte
        putCat("t-240021",   "ka2.category.nachbarschaft_und_stadtteil");                           // FrKr
        putCat("t-ka-kat11", "ka2.category.nachbarschaft_und_stadtteil");                           // TeSch
        putCat("t-230441",   "ka2.category.nachbarschaft_und_stadtteil");                           // TreKö
        putCat("t-202860",   "ka2.category.nachbarschaft_und_stadtteil");                           // ChaWi
        putCat("t-96806",    "ka2.category.nachbarschaft_und_stadtteil");                           // Span
        putCat("t-215495",   "ka2.category.nachbarschaft_und_stadtteil");                           // Li
        putCat("t-376353",   "ka2.category.nachbarschaft_und_stadtteil");                           // Li
        putCat("t-266441",   "ka2.category.netzwerk");                                              // Mitte
        putCat("t-777381",   "ka2.category.netzwerk_fruehe_hilfen");                                // Pankow
        putCat("t-253534",   "ka2.category.notdienste");                                            // Mitte
        putCat("t-240022",   "ka2.category.notdienste");                                            // FrKr
        putCat("t-ka-kat13", "ka2.category.notdienste");                                            // TeSch
        putCat("t-230442",   "ka2.category.notdienste");                                            // TreKö
        putCat("t-202861",   "ka2.category.notdienste");                                            // ChaWi
        putCat("t-96807",    "ka2.category.notdienste");                                            // Span
        putCat("t-308025",   "ka2.category.notdienste");                                            // SteZe
        putCat("t-189002",   "ka2.category.notdienste");                                            // Li
        putCat("t-305613",   "ka2.category.pflege");                                                // TeSch
        putCat("t-181735",   "ka2.category.politik");                                               // Neuk
        putCat("t-253535",   "ka2.category.schule");                                                // Mitte
        putCat("t-240023",   "ka2.category.schule");                                                // FrKr
        putCat("t-ka-kat14", "ka2.category.schule");                                                // TeSch
        putCat("t-230443",   "ka2.category.schule");                                                // TreKö
        putCat("t-181736",   "ka2.category.schule");                                                // Neuk
        putCat("t-181746",   "ka2.category.schule");                                                // Neuk
        putCat("t-230580",   "ka2.category.schule");                                                // Pankow
        putCat("t-202862",   "ka2.category.schule");                                                // ChaWi
        putCat("t-96808",    "ka2.category.schule");                                                // Span
        putCat("t-569790",   "ka2.category.schule");                                                // SteZe
        putCat("t-188996",   "ka2.category.schule");                                                // Li
        putCat("t-266443",   "ka2.category.seniorinnen_und_senioren");                              // Mitte
        putCat("t-240026",   "ka2.category.seniorinnen_und_senioren");                              // FrKr
        putCat("t-ka-kat4",  "ka2.category.seniorinnen_und_senioren");                              // TeSch
        putCat("t-230444",   "ka2.category.seniorinnen_und_senioren");                              // TreKö
        putCat("t-96809",    "ka2.category.seniorinnen_und_senioren");                              // Span
        putCat("t-308027",   "ka2.category.seniorinnen_und_senioren");                              // SteZe
        putCat("t-189003",   "ka2.category.seniorinnen_und_senioren");                              // Li
        putCat("t-181738",   "ka2.category.sonstiges");                                             // Neuk
        putCat("t-230578",   "ka2.category.sonstiges");                                             // Pankow
        putCat("t-189004",   "ka2.category.soziale_einrichtungen_und_dienste");                     // Li
        putCat("t-240025",   "ka2.category.spezielle_angebote_fuer_migranten_und_migrantinnen");    // FrKr
        putCat("t-230585",   "ka2.category.spielplaetze");                                          // Pankow
        putCat("t-894927",   "ka2.category.spielplaetze");                                          // ChaWi
        putCat("t-569791",   "ka2.category.spielplaetze");                                          // SteZe
        putCat("t-266440",   "ka2.category.sport");                                                 // Mitte
        putCat("t-240024",   "ka2.category.sport");                                                 // FrKr
        putCat("t-ka-kat15", "ka2.category.sport");                                                 // TeSch
        putCat("t-230445",   "ka2.category.sport");                                                 // TreKö
        putCat("t-181744",   "ka2.category.sport");                                                 // Neuk
        putCat("t-230581",   "ka2.category.sport");                                                 // Pankow
        putCat("t-202864",   "ka2.category.sport");                                                 // ChaWi
        putCat("t-96810",    "ka2.category.sport");                                                 // Span
        putCat("t-308028",   "ka2.category.sport");                                                 // SteZe
        putCat("t-189005",   "ka2.category.sport");                                                 // Li
        putCat("t-230591",   "ka2.category.sport");                                                 // Li
        putCat("t-256208",   "ka2.category.standorte_des_bezirksamtes");                            // Pankow
        putCat("t-308191",   "ka2.category.standorte_des_bezirksamtes");                            // SteZe
        putCat("t-308193",   "ka2.category.standorte_des_bezirksamtes");                            // SteZe
        putCat("t-646940",   "ka2.category.standorte_des_bezirksamtes");                            // SteZe
        putCat("t-646944",   "ka2.category.standorte_des_bezirksamtes");                            // SteZe
        putCat("t-645803",   "ka2.category.standorte_des_bezirksamtes");                            // SteZe
        putCat("t-552214",   "ka2.category.standorte_des_bezirksamtes");                            // SteZe
        putCat("t-646946",   "ka2.category.standorte_des_bezirksamtes");                            // SteZe
        putCat("t-646947",   "ka2.category.standorte_des_bezirksamtes");                            // SteZe
        putCat("t-308188",   "ka2.category.standorte_des_bezirksamtes");                            // SteZe
        putCat("t-308183",   "ka2.category.standorte_des_bezirksamtes");                            // SteZe
        putCat("t-308189",   "ka2.category.standorte_des_bezirksamtes");                            // SteZe
        putCat("t-308186",   "ka2.category.standorte_des_bezirksamtes");                            // SteZe
        putCat("t-308184",   "ka2.category.standorte_des_bezirksamtes");                            // SteZe
        putCat("t-308185",   "ka2.category.standorte_des_bezirksamtes");                            // SteZe
        putCat("t-680565",   "ka2.category.standorte_des_bezirksamtes");                            // SteZe
        putCat("t-646950",   "ka2.category.standorte_des_bezirksamtes");                            // SteZe
        putCat("t-308192",   "ka2.category.standorte_des_bezirksamtes");                            // SteZe
        putCat("t-308187",   "ka2.category.standorte_des_bezirksamtes");                            // SteZe
        putCat("t-308190",   "ka2.category.standorte_des_bezirksamtes");                            // SteZe
        putCat("t-646951",   "ka2.category.standorte_des_bezirksamtes");                            // SteZe
        putCat("t-646952",   "ka2.category.standorte_des_bezirksamtes");                            // SteZe
        putCat("t-646953",   "ka2.category.standorte_des_bezirksamtes");                            // SteZe
        putCat("t-214508",   "ka2.category.standorte_des_bezirksamtes");                            // Li
        putCat("t-214509",   "ka2.category.standorte_des_bezirksamtes");                            // Li
        putCat("t-214499",   "ka2.category.standorte_des_bezirksamtes");                            // Li
        putCat("t-214506",   "ka2.category.standorte_des_bezirksamtes");                            // Li
        putCat("t-214487",   "ka2.category.standorte_des_bezirksamtes");                            // Li
        putCat("t-214484",   "ka2.category.standorte_des_bezirksamtes");                            // Li
        putCat("t-214504",   "ka2.category.standorte_des_bezirksamtes");                            // Li
        putCat("t-214505",   "ka2.category.standorte_des_bezirksamtes");                            // Li
        putCat("t-214511",   "ka2.category.standorte_des_bezirksamtes");                            // Li
        putCat("t-1014206",  "ka2.category.standorte_des_bezirksamtes");                            // Li
        putCat("t-214510",   "ka2.category.standorte_des_bezirksamtes");                            // Li
        putCat("t-214512",   "ka2.category.standorte_des_bezirksamtes");                            // Li
        putCat("t-330478",   "ka2.category.standorte_des_bezirksamtes");                            // Li
        putCat("t-230579",   "ka2.category.standorte_des_jugendamtes");                             // Pankow
        putCat("t-181737",   "ka2.category.tagesbetreuung");                                        // Neuk
        putCat("t-230584",   "ka2.category.umwelt_und_natur");                                      // Pankow
        putCat("t-308029",   "ka2.category.umwelt_und_natur");                                      // SteZe
        putCat("t-206811",   "ka2.category.umwelt_und_natur");                                      // Li
        putCat("t-181747",   "ka2.category.verwaltung");                                            // Neuk
        putCat("t-794601",   "ka2.category.weltanschauung");                                        // ChaWi
        putCat("t-308030",   "ka2.category.weltanschauung");                                        // SteZe
        putCat("t-189006",   "ka2.category.weltanschauung");                                        // Li
        putCat("t-266442",   "ka2.category.wohnung_und_unterkunft");                                // Mitte
        putCat("t-ka-kat16", "ka2.category.wohnung_und_unterkunft");                                // TeSch
        putCat("t-230446",   "ka2.category.wohnung_und_unterkunft");                                // TreKö
        putCat("t-202865",   "ka2.category.wohnung_und_unterkunft");                                // ChaWi
        putCat("t-96811",    "ka2.category.wohnung_und_unterkunft");                                // Span
        putCat("t-1281580",  "ka2.category.wohnung_und_unterkunft");                                // Li

        // Angebote
        putCat("t-240053",   "ka2.category.aerzte");                                                    // FrKr
        putCat("t-189018",   "ka2.category.angebote_des_jugendamtes");                                  // Li
        putCat("t-189014",   "ka2.category.angebote_fuer_frauen");                                      // Li
        putCat("t-189017",   "ka2.category.angebote_fuer_jugendliche");                                 // Li
        putCat("t-189019",   "ka2.category.angebote_fuer_kinder");                                      // Li
        putCat("t-253548",   "ka2.category.angebote_fuer_menschen_mit_behinderung");                    // Mitte
        putCat("t-240059",   "ka2.category.angebote_fuer_menschen_mit_behinderung");                    // FrKr
        putCat("t-230632",   "ka2.category.angebote_fuer_menschen_mit_behinderung");                    // Pankow
        putCat("t-189016",   "ka2.category.angebote_fuer_menschen_mit_behinderung");                    // Li
        putCat("t-189026",   "ka2.category.angebote_fuer_senioren");                                    // Li
        putCat("t-240041",   "ka2.category.angebote_in_familienbildung_elternbildung_familienselbsthilfe_familienberatung_familienerholung");   // FrKr
        putCat("t-189013",   "ka2.category.angebote_in_familienbildung_elternbildung_familienselbsthilfe_familienberatung_familienerholung");   // Li
        putCat("t-205729",   "ka2.category.angebote_in_kultur_und_bildungseinrichtungen");              // Li
        putCat("t-240083",   "ka2.category.babysitter");                                                // FrKr
        putCat("t-240038",   "ka2.category.beratung_bei_trennung_und_scheidung");                       // FrKr
        putCat("t-240094",   "ka2.category.beratung_und_hilfe_in_krisensituationen");                   // FrKr
        putCat("t-189025",   "ka2.category.beratung_und_hilfe_in_krisensituationen");                   // Li
        putCat("t-253549",   "ka2.category.beratungsangebote");                                         // Mitte
        putCat("t-ka-ang1",  "ka2.category.beratungsangebote");                                         // TeSch
        putCat("t-230630",   "ka2.category.beratungsangebote");                                         // Pankow
        putCat("t-202867",   "ka2.category.beratungsangebote");                                         // ChaWi
        putCat("t-103804",   "ka2.category.beratungsangebote");                                         // Span
        putCat("t-189011",   "ka2.category.beratungsangebote");                                         // Li
        putCat("t-240028",   "ka2.category.berufsausbildung");                                          // FrKr
        putCat("t-189008",   "ka2.category.berufsausbildung");                                          // Li
        putCat("t-240036",   "ka2.category.berufsberatung_und_orientierung");                           // FrKr
        putCat("t-240065",   "ka2.category.berufsberatung_und_orientierung");                           // FrKr
        putCat("t-95413",    "ka2.category.beschaeftigungstagesstaette_fuer_alkoholkranke");            // TeSch
        putCat("t-202868",   "ka2.category.beschaeftigungstagesstaette_fuer_alkoholkranke");            // ChaWi
        putCat("t-103805",   "ka2.category.beschaeftigungstagesstaette_fuer_alkoholkranke");            // Span
        putCat("t-95414",    "ka2.category.betreutes_einzelwohnen");                                    // TeSch
        putCat("t-202869",   "ka2.category.betreutes_einzelwohnen");                                    // ChaWi
        putCat("t-96812",    "ka2.category.betreutes_einzelwohnen");                                    // Span
        putCat("t-ka-ang2",  "ka2.category.betreuung");                                                 // TeSch
        putCat("t-202870",   "ka2.category.betreuung");                                                 // ChaWi
        putCat("t-103806",   "ka2.category.betreuung");                                                 // Span
        putCat("t-308046",   "ka2.category.botschaften");                                               // SteZe
        putCat("t-240034",   "ka2.category.drogenberatung");                                            // FrKr
        putCat("t-240058",   "ka2.category.drogenentzugseinrichtung");                                  // FrKr
        putCat("t-266732",   "ka2.category.eltern_kind_gruppen");                                       // FrKr
        putCat("t-240060",   "ka2.category.fallmanagement_jugendamt_behindertenhilfe");                 // FrKr
        putCat("t-189036",   "ka2.category.angebote_fuer_erwachsene");                                  // Li
        putCat("t-ka-ang3",  "ka2.category.essen");                                                     // TeSch
        putCat("t-202871",   "ka2.category.essen");                                                     // ChaWi
        putCat("t-96813",    "ka2.category.essen");                                                     // Span
        putCat("t-253550",   "ka2.category.familien_und_erziehungsberatung");                           // Mitte
        putCat("t-240070",   "ka2.category.familien_und_erziehungsberatung");                           // FrKr
        putCat("t-240040",   "ka2.category.familien_und_erziehungsberatung");                           // FrKr
        putCat("t-230614",   "ka2.category.familien_und_erziehungsberatung");                           // Pankow
        putCat("t-240043",   "ka2.category.familiencafes");                                             // FrKr
        putCat("t-240049",   "ka2.category.familienkasse");                                             // FrKr
        putCat("t-240042",   "ka2.category.familienzentren");                                           // FrKr
        putCat("t-308043",   "ka2.category.feuerwehr");                                                 // SteZe
        putCat("t-215651",   "ka2.category.feuerwehr");                                                 // Li
        putCat("t-308044",   "ka2.category.finanzamt");                                                 // SteZe
        putCat("t-215598",   "ka2.category.finanzamt");                                                 // Li
        putCat("t-240030",   "ka2.category.fort_und_weiterbildungen");                                  // FrKr
        putCat("t-96696",    "ka2.category.fort_und_weiterbildungen");                                  // TeSch
        putCat("t-202892",   "ka2.category.fort_und_weiterbildungen");                                  // ChaWi
        putCat("t-103825",   "ka2.category.fort_und_weiterbildungen");                                  // Span
        putCat("t-189010",   "ka2.category.fort_und_weiterbildungen");                                  // Li
        putCat("t-240050",   "ka2.category.frauenhaeuser");                                             // FrKr
        putCat("t-253551",   "ka2.category.frauenprojekte");                                            // Mitte
        putCat("t-230615",   "ka2.category.frauenprojekte");                                            // Pankow
        putCat("t-96740",    "ka2.category.freizeit_und_beschaeftigung_fuer_kinder_und_jugendliche");   // TeSch
        putCat("t-202872",   "ka2.category.freizeit_und_beschaeftigung_fuer_kinder_und_jugendliche");   // ChaWi
        putCat("t-103807",   "ka2.category.freizeit_und_beschaeftigung_fuer_kinder_und_jugendliche");   // Span
        putCat("t-95142",    "ka2.category.freizeit_und_beschaeftigung_fuer_seniorinnen_und_senioren"); // TeSch
        putCat("t-202873",   "ka2.category.freizeit_und_beschaeftigung_fuer_seniorinnen_und_senioren"); // ChaWi
        putCat("t-103808",   "ka2.category.freizeit_und_beschaeftigung_fuer_seniorinnen_und_senioren"); // Span
        putCat("t-96749",    "ka2.category.ganzheitliche_bildung_und_erziehung");                       // TeSch
        putCat("t-202874",   "ka2.category.ganzheitliche_bildung_und_erziehung");                       // ChaWi
        putCat("t-103809",   "ka2.category.ganzheitliche_bildung_und_erziehung");                       // Span
        putCat("t-240056",   "ka2.category.geburtshaeuser");                                            // FrKr
        putCat("t-305625",   "ka2.category.generationsuebergreifendes_wohnen");                         // TeSch
        putCat("t-215631",   "ka2.category.gerichte");                                                  // Li
        putCat("t-305622",   "ka2.category.gesetzliche_betreuung");                                     // TeSch
        putCat("t-240051",   "ka2.category.gezielte_gesundheitsfoerderung");                            // FrKr
        putCat("t-189015",   "ka2.category.gezielte_gesundheitsfoerderung");                            // Li
        putCat("t-240082",   "ka2.category.grosselterndienst");                                         // FrKr
        putCat("t-240097",   "ka2.category.grund_und_oberschulen");                                     // FrKr
        putCat("t-253552",   "ka2.category.grundschulen");                                              // Mitte
        putCat("t-230587",   "ka2.category.grundschulen");                                              // Pankow
        putCat("t-266731",   "ka2.category.hausaufgabenbetreuung");                                     // FrKr
        putCat("t-240055",   "ka2.category.hebammen");                                                  // FrKr
        putCat("t-240047",   "ka2.category.hilfen_in_besonderen_notsituationen");                       // FrKr
        putCat("t-253553",   "ka2.category.hilfen_zur_erziehung");                                      // Mitte
        putCat("t-240073",   "ka2.category.hilfen_zur_erziehung");                                      // FrKr
        putCat("t-230612",   "ka2.category.hilfen_zur_erziehung");                                      // Pankow
        putCat("t-202895",   "ka2.category.hilfen_zur_erziehung");                                      // ChaWi
        putCat("t-97314",    "ka2.category.hilfen_zur_erziehung");                                      // Span
        putCat("t-240057",   "ka2.category.hiv_beratung");                                              // FrKr
        putCat("t-794603",   "ka2.category.hort");                                                      // ChaWi
        putCat("t-240096",   "ka2.category.hotline");                                                   // FrKr
        putCat("t-240031",   "ka2.category.jobcenter_agentur_fuer_arbeit");                             // FrKr
        putCat("t-308042",   "ka2.category.jobcenter_agentur_fuer_arbeit");                             // SteZe
        putCat("t-215599",   "ka2.category.jobcenter_agentur_fuer_arbeit");                             // Li
        putCat("t-253554",   "ka2.category.jugendberatung_und_jugendberufshilfe");                      // Mitte
        putCat("t-230613",   "ka2.category.jugendberatung_und_jugendberufshilfe");                      // Pankow
        putCat("t-183042",   "ka2.category.jugendfeuerwehr");                                           // TeSch
        putCat("t-240062",   "ka2.category.jugendfreizeiteinrichtungen");                               // FrKr
        putCat("t-240074",   "ka2.category.jugendgerichtshilfe_und_bewaehrungshilfe");                  // FrKr
        putCat("t-240067",   "ka2.category.jugendgerichtshilfe_und_bewaehrungshilfe");                  // FrKr
        putCat("t-240066",   "ka2.category.jugendnotdienst");                                           // FrKr
        putCat("t-240063",   "ka2.category.jugendsozialarbeit");                                        // FrKr
        putCat("t-215641",   "ka2.category.kfz_zulassungsstelle");                                      // Li
        putCat("t-240087",   "ka2.category.kieznahe_mehrgenerationsangebote");                          // FrKr
        putCat("t-189024",   "ka2.category.kieznahe_mehrgenerationsangebote");                          // Li
        putCat("t-240054",   "ka2.category.kinder_und_jugendgesundheitsdienste");                       // FrKr
        putCat("t-240095",   "ka2.category.kinder_und_jugendnotdienst");                                // FrKr
        putCat("t-240039",   "ka2.category.kinder_und_jugendpsychiatrische_beratungsstelle");           // FrKr
        putCat("t-879767",   "ka2.category.kinderbetreuung_an_schulen");                                // ChaWi
        putCat("t-240075",   "ka2.category.kinderfreizeiteinrichtungen");                               // FrKr
        putCat("t-240077",   "ka2.category.kindernotdienst");                                           // FrKr
        putCat("t-240076",   "ka2.category.kinderschutzteam");                                          // FrKr
        putCat("t-240045",   "ka2.category.kinderspielplaetze");                                        // FrKr
        putCat("t-306996",   "ka2.category.kindertagespflege");                                         // TeSch
        putCat("t-240085",   "ka2.category.kirchen_und_religionsgemeinschaften");                       // FrKr
        putCat("t-240068",   "ka2.category.kjpd");                                                      // FrKr
        putCat("t-95491",    "ka2.category.kleiderkammer");                                             // TeSch
        putCat("t-202875",   "ka2.category.kleiderkammer");                                             // ChaWi
        putCat("t-103810",   "ka2.category.kleiderkammer");                                             // Span
        putCat("t-95126",    "ka2.category.kochen");                                                    // TeSch
        putCat("t-202876",   "ka2.category.kochen");                                                    // ChaWi
        putCat("t-103811",   "ka2.category.kochen");                                                    // Span
        putCat("t-ka-ang4",  "ka2.category.kontakte");                                                  // TeSch
        putCat("t-202877",   "ka2.category.kontakte");                                                  // ChaWi
        putCat("t-103812",   "ka2.category.kontakte");                                                  // Span
        putCat("t-240052",   "ka2.category.krankenhaeuser");                                            // FrKr
        putCat("t-240084",   "ka2.category.kultur_und_bildungseinrichtungen");                          // FrKr
        putCat("t-305623",   "ka2.category.kurzzeitpflegeeinrichtungen");                               // TeSch
        putCat("t-240069",   "ka2.category.leitung_und_team_des_jugendamtes");                          // FrKr
        putCat("t-240079",   "ka2.category.logopaedische_praxen");                                      // FrKr
        putCat("t-ka-ang5",  "ka2.category.medien_und_computer");                                       // TeSch
        putCat("t-202878",   "ka2.category.medien_und_computer");                                       // ChaWi
        putCat("t-103813",   "ka2.category.medien_und_computer");                                       // Span
        putCat("t-240037",   "ka2.category.mietberatung");                                              // FrKr
        putCat("t-253555",   "ka2.category.angebot_migration_und_integration");                         // Mitte
        putCat("t-230628",   "ka2.category.angebot_migration_und_integration");                         // Pankow
        putCat("t-305626",   "ka2.category.mobilitaetsdienst");                                         // TeSch
        putCat("t-240086",   "ka2.category.musikschulen_und_vhs");                                      // FrKr
        putCat("t-230616",   "ka2.category.nachbarschaftszentren");                                     // Pankow
        putCat("t-253556",   "ka2.category.oberschulen");                                               // Mitte
        putCat("t-230588",   "ka2.category.oberschulen");                                               // Pankow
        putCat("t-240088",   "ka2.category.offene_treffpunkte_mit_sozialkulturellem_charakter");        // FrKr
        putCat("t-306042",   "ka2.category.pflegedienste");                                             // TeSch
        putCat("t-305619",   "ka2.category.pflegeheime");                                               // TeSch
        putCat("t-308047",   "ka2.category.polizei");                                                   // SteZe
        putCat("t-214773",   "ka2.category.polizei");                                                   // Li
        putCat("t-ka-ang6",  "ka2.category.qualifizierung_ausbildung_weiterbildung");                   // TeSch
        putCat("t-202879",   "ka2.category.qualifizierung_ausbildung_weiterbildung");                   // ChaWi
        putCat("t-103814",   "ka2.category.qualifizierung_ausbildung_weiterbildung");                   // Span
        putCat("t-240029",   "ka2.category.qualifizierung_und_beschaeftigung");                         // FrKr
        putCat("t-189009",   "ka2.category.qualifizierung_und_beschaeftigung");                         // Li
        putCat("t-240090",   "ka2.category.quartiersmanagement");                                       // FrKr
        putCat("t-ka-ang7",  "ka2.category.raeume_freiraumnutzung");                                    // TeSch
        putCat("t-202880",   "ka2.category.raeume_freiraumnutzung");                                    // ChaWi
        putCat("t-103815",   "ka2.category.raeume_freiraumnutzung");                                    // Span
        putCat("t-240035",   "ka2.category.rechtsberatung");                                            // FrKr
        putCat("t-240072",   "ka2.category.regionale_dienste");                                         // FrKr
        putCat("t-240061",   "ka2.category.reha_im_jobcenter_arbeitsamt");                              // FrKr
        putCat("t-240098",   "ka2.category.schulbezogene_angebote_der_jugendhilfe");                    // FrKr
        putCat("t-253557",   "ka2.category.schuldner_und_insolvenzberatung");                           // Mitte
        putCat("t-240032",   "ka2.category.schuldner_und_insolvenzberatung");                           // FrKr
        putCat("t-230629",   "ka2.category.schuldner_und_insolvenzberatung");                           // Pankow
        putCat("t-253558",   "ka2.category.schulpsychologische_beratungsstelle");                       // Mitte
        putCat("t-230635",   "ka2.category.schulpsychologische_beratungsstelle");                       // Pankow
        putCat("t-306995",   "ka2.category.schulsozialarbeit");                                         // TeSch
        putCat("t-255713",   "ka2.category.schulsporthalle");                                           // FrKr
        putCat("t-255714",   "ka2.category.schwimmbad");                                                // FrKr
        putCat("t-240093",   "ka2.category.selbsthilfegruppen");                                        // FrKr
        putCat("t-305621",   "ka2.category.seniorenwohnanlage");                                        // TeSch
        putCat("t-ka-ang13", "ka2.category.sonstige");                                                  // TeSch
        putCat("t-202881",   "ka2.category.sonstige");                                                  // ChaWi
        putCat("t-103816",   "ka2.category.sonstige");                                                  // Span
        putCat("t-253559",   "ka2.category.sonstige_schulen");                                          // Mitte
        putCat("t-230589",   "ka2.category.sonstige_schulen");                                          // Pankow
        putCat("t-95117",    "ka2.category.sozial_kulturelle_projekte");                                // TeSch
        putCat("t-202882",   "ka2.category.sozial_kulturelle_projekte");                                // ChaWi
        putCat("t-103817",   "ka2.category.sozial_kulturelle_projekte");                                // Span
        putCat("t-95468",    "ka2.category.sozialbetreutes_wohnen");                                    // TeSch
        putCat("t-202883",   "ka2.category.sozialbetreutes_wohnen");                                    // ChaWi
        putCat("t-103818",   "ka2.category.sozialbetreutes_wohnen");                                    // Span
        putCat("t-240033",   "ka2.category.sozialhilfeberatung");                                       // FrKr
        putCat("t-189012",   "ka2.category.spezialberatung");                                           // Li
        putCat("t-ka-ang8",  "ka2.category.spielzeug_sportgeraete_spielplatz_sportplatz");              // TeSch
        putCat("t-202884",   "ka2.category.spielzeug_sportgeraete_spielplatz_sportplatz");              // ChaWi
        putCat("t-103819",   "ka2.category.spielzeug_sportgeraete_spielplatz_sportplatz");              // Span
        putCat("t-240099",   "ka2.category.sport_und_bolzplaetze");                                     // FrKr
        putCat("t-189027",   "ka2.category.sportangebote");                                             // Li
        putCat("t-240101",   "ka2.category.sportbezogene_jugendfreizeitangebote");                      // FrKr
        putCat("t-240100",   "ka2.category.sportvereine");                                              // FrKr
        putCat("t-754271",   "ka2.category.stadtreinigung");                                            // SteZe
        putCat("t-240089",   "ka2.category.stadtteilarbeit");                                           // FrKr
        putCat("t-240092",   "ka2.category.streetworker");                                              // FrKr
        putCat("t-240080",   "ka2.category.tagesbetreuung_fuer_kinder");                                // FrKr
        putCat("t-240081",   "ka2.category.tagesbetreuung_fuer_kinder");                                // FrKr
        putCat("t-189021",   "ka2.category.tagesbetreuung_fuer_kinder");                                // Li
        putCat("t-189020",   "ka2.category.tageseinrichtung_fuer_kinder");                              // Li
        putCat("t-305624",   "ka2.category.tagespflegeeinrichtungen");                                  // TeSch
        putCat("t-1037011",  "ka2.category.tagespflegestelle");                                         // TeSch
        putCat("t-ka-ang9",  "ka2.category.technische_geraete_werkzeuge_werkstaetten");                 // TeSch
        putCat("t-202885",   "ka2.category.technische_geraete_werkzeuge_werkstaetten");                 // ChaWi
        putCat("t-103820",   "ka2.category.technische_geraete_werkzeuge_werkstaetten");                 // Span
        putCat("t-95412",    "ka2.category.therapeutische_wohngemeinschaft");                           // TeSch
        putCat("t-202886",   "ka2.category.therapeutische_wohngemeinschaft");                           // ChaWi
        putCat("t-103821",   "ka2.category.therapeutische_wohngemeinschaft");                           // Span
        putCat("t-240044",   "ka2.category.traeger_der_jugendhilfe");                                   // FrKr
        putCat("t-ka-ang10", "ka2.category.transportmoeglichkeiten");                                   // TeSch
        putCat("t-202888",   "ka2.category.transportmoeglichkeiten");                                   // ChaWi
        putCat("t-103822",   "ka2.category.transportmoeglichkeiten");                                   // Span
        putCat("t-206809",   "ka2.category.umweltbildung_und_umweltberatung");                          // Li
        putCat("t-240048",   "ka2.category.unterhalt_vaterschaftsanerkennung_im_jugendamt");            // FrKr
        putCat("t-ka-ang11", "ka2.category.unterhaltung");                                              // TeSch
        putCat("t-202889",   "ka2.category.unterhaltung");                                              // ChaWi
        putCat("t-103823",   "ka2.category.unterhaltung");                                              // Span
        putCat("t-ka-ang12", "ka2.category.vermittlung_von_jobs_nachbarschaftshilfe");                  // TeSch
        putCat("t-202891",   "ka2.category.vermittlung_von_jobs_nachbarschaftshilfe");                  // ChaWi
        putCat("t-103824",   "ka2.category.vermittlung_von_jobs_nachbarschaftshilfe");                  // Span
        putCat("t-262210",   "ka2.category.wohnen");                                                    // FrKr
        putCat("t-305620",   "ka2.category.wohngemeinschaft_fuer_demenzkranke");                        // TeSch
        putCat("t-305627",   "ka2.category.wohngemeinschaft_fuer_pflegebeduerftige");                   // TeSch

        // Zielgruppen
        putCat("t-96750",    "ka2.category.0_bis_6_jahre");                                             // TeSch
        putCat("t-202898",   "ka2.category.0_bis_6_jahre");                                             // ChaWi
        putCat("t-96814",    "ka2.category.0_bis_6_jahre");                                             // Span
        putCat("t-96733",    "ka2.category.2_bis_6_jahre");                                             // TeSch
        putCat("t-202900",   "ka2.category.2_bis_6_jahre");                                             // ChaWi
        putCat("t-96815",    "ka2.category.2_bis_6_jahre");                                             // Span
        putCat("t-202903",   "ka2.category.6_bis_10_jahre");                                            // ChaWi
        putCat("t-106026",   "ka2.category.6_bis_10_jahre");                                            // Span
        putCat("t-97135",    "ka2.category.11_bis_14_jahre");                                           // TeSch
        putCat("t-202899",   "ka2.category.11_bis_14_jahre");                                           // ChaWi
        putCat("t-103827",   "ka2.category.11_bis_14_jahre");                                           // Span
        putCat("t-97127",    "ka2.category.ab_14_jahre");                                               // TeSch
        putCat("t-202905",   "ka2.category.ab_14_jahre");                                               // ChaWi
        putCat("t-103828",   "ka2.category.ab_14_jahre");                                               // Span
        putCat("t-253538",   "ka2.category.alle_altersgruppen");                                        // Mitte
        putCat("t-240105",   "ka2.category.alle_altersgruppen");                                        // FrKr
        putCat("t-ka-alt10", "ka2.category.alle_altersgruppen");                                        // TeSch
        putCat("t-230448",   "ka2.category.alle_altersgruppen");                                        // TreKö
        putCat("t-230593",   "ka2.category.alle_altersgruppen");                                        // Pankow
        putCat("t-202906",   "ka2.category.alle_altersgruppen");                                        // ChaWi
        putCat("t-96816",    "ka2.category.alle_altersgruppen");                                        // Span
        putCat("t-308032",   "ka2.category.alle_altersgruppen");                                        // SteZe
        putCat("t-189029",   "ka2.category.alle_altersgruppen");                                        // Li
        putCat("t-240106",   "ka2.category.auszubildende");                                             // FrKr
        putCat("t-253539",   "ka2.category.auszubildende_und_junge_erwachsene");                        // Mitte
        putCat("t-ka-alt7",  "ka2.category.auszubildende_und_junge_erwachsene");                        // TeSch
        putCat("t-230449",   "ka2.category.auszubildende_und_junge_erwachsene");                        // TreKö
        putCat("t-230594",   "ka2.category.auszubildende_und_junge_erwachsene");                        // Pankow
        putCat("t-202907",   "ka2.category.auszubildende_und_junge_erwachsene");                        // ChaWi
        putCat("t-103829",   "ka2.category.auszubildende_und_junge_erwachsene");                        // Span
        putCat("t-308033",   "ka2.category.auszubildende_und_junge_erwachsene");                        // SteZe
        putCat("t-189032",   "ka2.category.auszubildende_und_junge_erwachsene");                        // Li
        putCat("t-253540",   "ka2.category.erwachsene");                                                // Mitte
        putCat("t-240108",   "ka2.category.erwachsene");                                                // FrKr
        putCat("t-ka-alt8",  "ka2.category.erwachsene");                                                // TeSch
        putCat("t-230450",   "ka2.category.erwachsene");                                                // TreKö
        putCat("t-230595",   "ka2.category.erwachsene");                                                // Pankow
        putCat("t-202908",   "ka2.category.erwachsene");                                                // ChaWi
        putCat("t-103830",   "ka2.category.erwachsene");                                                // Span
        putCat("t-192210",   "ka2.category.erwachsene");                                                // Li
        putCat("t-240109",   "ka2.category.familien");                                                  // FrKr
        putCat("t-253541",   "ka2.category.familien_und_alleinerziehende_mit_kindern_im_schulalter");   // Mitte
        putCat("t-240111",   "ka2.category.familien_und_alleinerziehende_mit_kindern_im_schulalter");   // FrKr
        putCat("t-ka-alt3",  "ka2.category.familien_und_alleinerziehende_mit_kindern_im_schulalter");   // TeSch
        putCat("t-230451",   "ka2.category.familien_und_alleinerziehende_mit_kindern_im_schulalter");   // TreKö
        putCat("t-230596",   "ka2.category.familien_und_alleinerziehende_mit_kindern_im_schulalter");   // Pankow
        putCat("t-202909",   "ka2.category.familien_und_alleinerziehende_mit_kindern_im_schulalter");   // ChaWi
        putCat("t-103831",   "ka2.category.familien_und_alleinerziehende_mit_kindern_im_schulalter");   // Span
        putCat("t-308034",   "ka2.category.familien_und_alleinerziehende_mit_kindern_im_schulalter");   // SteZe
        putCat("t-189035",   "ka2.category.familien_und_alleinerziehende_mit_kindern_im_schulalter");   // Li
        putCat("t-253542",   "ka2.category.familien_und_alleinerziehende_mit_kleinkindern");            // Mitte
        putCat("t-240112",   "ka2.category.familien_und_alleinerziehende_mit_kleinkindern");            // FrKr
        putCat("t-ka-alt2",  "ka2.category.familien_und_alleinerziehende_mit_kleinkindern");            // TeSch
        putCat("t-230452",   "ka2.category.familien_und_alleinerziehende_mit_kleinkindern");            // TreKö
        putCat("t-230597",   "ka2.category.familien_und_alleinerziehende_mit_kleinkindern");            // Pankow
        putCat("t-202910",   "ka2.category.familien_und_alleinerziehende_mit_kleinkindern");            // ChaWi
        putCat("t-103832",   "ka2.category.familien_und_alleinerziehende_mit_kleinkindern");            // Span
        putCat("t-308035",   "ka2.category.familien_und_alleinerziehende_mit_kleinkindern");            // SteZe
        putCat("t-189034",   "ka2.category.familien_und_alleinerziehende_mit_kleinkindern");            // Li
        putCat("t-253543",   "ka2.category.familien_und_alleinerziehende_mit_saeuglingen");             // Mitte
        putCat("t-240113",   "ka2.category.familien_und_alleinerziehende_mit_saeuglingen");             // FrKr
        putCat("t-ka-alt1",  "ka2.category.familien_und_alleinerziehende_mit_saeuglingen");             // TeSch
        putCat("t-230453",   "ka2.category.familien_und_alleinerziehende_mit_saeuglingen");             // TreKö
        putCat("t-230598",   "ka2.category.familien_und_alleinerziehende_mit_saeuglingen");             // Pankow
        putCat("t-202912",   "ka2.category.familien_und_alleinerziehende_mit_saeuglingen");             // ChaWi
        putCat("t-103833",   "ka2.category.familien_und_alleinerziehende_mit_saeuglingen");             // Span
        putCat("t-308036",   "ka2.category.familien_und_alleinerziehende_mit_saeuglingen");             // SteZe
        putCat("t-189033",   "ka2.category.familien_und_alleinerziehende_mit_saeuglingen");             // Li
        putCat("t-253544",   "ka2.category.zielgruppe_frauen");                                         // Mitte
        putCat("t-240114",   "ka2.category.zielgruppe_frauen");                                         // FrKr
        putCat("t-230639",   "ka2.category.zielgruppe_frauen");                                         // Pankow
        putCat("t-ka-alt6",  "ka2.category.jugendgruppen");                                             // TeSch
        putCat("t-202914",   "ka2.category.jugendgruppen");                                             // ChaWi
        putCat("t-103834",   "ka2.category.jugendgruppen");                                             // Span
        putCat("t-253545",   "ka2.category.jugendliche");                                               // Mitte
        putCat("t-240115",   "ka2.category.jugendliche");                                               // FrKr
        putCat("t-230454",   "ka2.category.jugendliche");                                               // TreKö
        putCat("t-230599",   "ka2.category.jugendliche");                                               // Pankow
        putCat("t-308037",   "ka2.category.jugendliche");                                               // SteZe
        putCat("t-189031",   "ka2.category.jugendliche");                                               // Li
        putCat("t-ka-alt5",  "ka2.category.jugendliche_selbstorganisierte");                            // TeSch
        putCat("t-202915",   "ka2.category.jugendliche_selbstorganisierte");                            // ChaWi
        putCat("t-103835",   "ka2.category.jugendliche_selbstorganisierte");                            // Span
        putCat("t-240107",   "ka2.category.junge_erwachsene");                                          // FrKr
        putCat("t-95469",    "ka2.category.junge_erwachsene");                                          // TeSch
        putCat("t-202916",   "ka2.category.junge_erwachsene");                                          // ChaWi
        putCat("t-103836",   "ka2.category.junge_erwachsene");                                          // Span
        putCat("t-240110",   "ka2.category.zielgruppe_kinder");                                         // FrKr
        putCat("t-253546",   "ka2.category.kinder_im_schulalter");                                      // Mitte
        putCat("t-240116",   "ka2.category.kinder_im_schulalter");                                      // FrKr
        putCat("t-ka-alt4",  "ka2.category.kinder_im_schulalter");                                      // TeSch
        putCat("t-230455",   "ka2.category.kinder_im_schulalter");                                      // TreKö
        putCat("t-230600",   "ka2.category.kinder_im_schulalter");                                      // Pankow
        putCat("t-202917",   "ka2.category.kinder_im_schulalter");                                      // ChaWi
        putCat("t-103837",   "ka2.category.kinder_im_schulalter");                                      // Span
        putCat("t-308038",   "ka2.category.kinder_im_schulalter");                                      // SteZe
        putCat("t-189030",   "ka2.category.kinder_im_schulalter");                                      // Li
        putCat("t-240117",   "ka2.category.zielgruppe_seniorinnen_und_senioren");                       // FrKr
        putCat("t-ka-alt9",  "ka2.category.zielgruppe_seniorinnen_und_senioren");                       // TeSch
        putCat("t-230456",   "ka2.category.zielgruppe_seniorinnen_und_senioren");                       // TreKö
        putCat("t-230610",   "ka2.category.zielgruppe_seniorinnen_und_senioren");                       // Pankow
        putCat("t-202918",   "ka2.category.zielgruppe_seniorinnen_und_senioren");                       // ChaWi
        putCat("t-103838",   "ka2.category.zielgruppe_seniorinnen_und_senioren");                       // Span
        putCat("t-308039",   "ka2.category.zielgruppe_seniorinnen_und_senioren");                       // SteZe
        putCat("t-192207",   "ka2.category.zielgruppe_seniorinnen_und_senioren");                       // Li
        putCat("t-253547",   "ka2.category.zielgruppe_sonstige");                                       // Mitte
        putCat("t-240118",   "ka2.category.zielgruppe_sonstige");                                       // FrKr
        putCat("t-ka-alt11", "ka2.category.zielgruppe_sonstige");                                       // TeSch
        putCat("t-230457",   "ka2.category.zielgruppe_sonstige");                                       // TreKö
        putCat("t-230601",   "ka2.category.zielgruppe_sonstige");                                       // Pankow
        putCat("t-202919",   "ka2.category.zielgruppe_sonstige");                                       // ChaWi
        putCat("t-103839",   "ka2.category.zielgruppe_sonstige");                                       // Span
        putCat("t-189037",   "ka2.category.zielgruppe_sonstige");                                       // Li

        // Träger
        putCat("t-181754",  "ka2.category.awo");                                                        // Neuk
        putCat("t-181751",  "ka2.category.diverse");                                                    // Neuk
        putCat("t-181756",  "ka2.category.dpw");                                                        // Neuk
        putCat("t-181755",  "ka2.category.drk");                                                        // Neuk
        putCat("t-181752",  "ka2.category.evangelisch");                                                // Neuk
        putCat("t-181753",  "ka2.category.katholisch");                                                 // Neuk
        putCat("t-181757",  "ka2.category.sonstige_traeger");                                           // Neuk
        putCat("t-181750",  "ka2.category.staedtisch");                                                 // Neuk

        // Überregional
        putCat("t-1220613", "ka2.category.berlinweit");                                                 // FrKr
        putCat("t-1220614", "ka2.category.gesamtbezirk");                                               // FrKr
    }

    private static void putCrit(String ka1CriteriaTypeId, String ka2FacetTypeUri) {
        if (CRITERIA_MAP.put(ka1CriteriaTypeId, ka2FacetTypeUri) != null) {
            throw new RuntimeException("More than one entry for KA1 criteria \"" + ka1CriteriaTypeId + "\"");
        }
    }

    private static void putCat(String ka1CategoryTopicId, String ka2CategoryUri) {
        if (CATEGORY_MAP.put(ka1CategoryTopicId, ka2CategoryUri) != null) {
            throw new RuntimeException("More than one entry for KA1 category \"" + ka1CategoryTopicId + "\"");
        }
    }
}
